

services:
  db:
    image: postgres:15-alpine
    container_name: saleor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saleor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: saleor-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: saleor-api
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/saleor"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
