version: "3"

services:
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: saleor-api
    ports:
      - 8000:8000
    depends_on:
      - saleor-db
      - saleor-redis
    environment:
      - DEBUG=True
    networks:
      - saleor_network

  saleor-db:
    image: postgres:15-alpine
    container_name: saleor-db
    ports:
      - 5432:5432
    networks:
      - saleor_network

  saleor-redis:
    image: redis:7.0-alpine
    container_name: saleor-redis
    ports:
      - 6379:6379
    networks:
      - saleor_network

  saleor-storefront:
    container_name: saleor-storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - saleor_network

networks:
  saleor_network:
    external: false
